### ISSUE TITLE
Associate a Gitter

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/gcc-datathon-2017#1]
Hi everyone,
Is it possible to add a Gitter badge in a way that we can chat about gcc-datathon-2017 on a gitter room and invite @slegras @jennaj @malloryfreeberg @frederikcoppens @MoHeydarian @bgruening @bebatut ... and me ;) ? It seems that I can't add a gitter badge by myself on this repo....

**Comment by dannon** [comment]
I just tried to create a 'private' gitter where we would invite people, but it is not possible (and I don't quite understand why).

If it's not a big deal that it's private, I'll just make a new 'hackathon-organizing' gitter that's open to the public, and all hack organizers can join.  I would like for both 'organizing teams' to be in the same room, so we can coordinate, unless someone opposes that idea.

**Comment by yvanlebras** [comment]
OK for me! @slegras ?

**Comment by jennaj** [comment]
What is the name of the room - still "hackathon-organizing"? I couldn't find it on gitter. Thanks!

**Comment by dannon** [comment]
I did not create it yet, was waiting on confirmation that a public room is fine.  I'll go ahead and make 'hackathon-organizing' and if we don't end up using it -- no big deal.

**Comment by dannon** [comment]
https://gitter.im/galaxyproject/hackathon-organizing

**Comment by slegras** [comment]
Sorry for my late answer!
It's OK for me :)
